server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.example.mopl: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

content:
  api:
    tmdb:
      key: ${CONTENT_API_TMDB_KEY}
      url: https://api.themoviedb.org/3
