server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: notification-group-v1

#캐시용 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1s
      connect-timeout: 2s
      database: 0

logging:
  level:
    org.example.mopl: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

sse:
  timeout: 3600000

content:
  api:
    tmdb:
      key: ${CONTENT_API_TMDB_KEY}
      url: https://api.themoviedb.org/3
