/* =========================
   users
========================= */
CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       uuid       UUID      NOT NULL,
                       email      VARCHAR   NOT NULL,
                       password   VARCHAR   NOT NULL,
                       locked     BOOLEAN,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP,
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uk_users_uuid UNIQUE (uuid),
                       CONSTRAINT uk_users_email UNIQUE (email)
);

/* =========================
   profiles (1:1 users)
========================= */
CREATE TABLE profiles (
                          id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          uuid              UUID      NOT NULL,
                          user_id           BIGINT    NOT NULL,
                          profile_image_url VARCHAR,
                          name              VARCHAR   NOT NULL,
                          created_at        TIMESTAMP NOT NULL,
                          updated_at        TIMESTAMP,
                          CONSTRAINT pk_profiles PRIMARY KEY (id),
                          CONSTRAINT uk_profiles_uuid UNIQUE (uuid),
                          CONSTRAINT uk_profiles_user UNIQUE (user_id)
);

/* =========================
   roles
========================= */
CREATE TABLE roles (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       uuid       UUID      NOT NULL,
                       name       VARCHAR   NOT NULL,
                       is_admin   BOOLEAN   NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP,
                       CONSTRAINT pk_roles PRIMARY KEY (id),
                       CONSTRAINT uk_roles_uuid UNIQUE (uuid),
                       CONSTRAINT uk_roles_name UNIQUE (name)
);

/* =========================
   user_roles (N:M)
========================= */
CREATE TABLE user_roles (
                            id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            user_id    BIGINT    NOT NULL,
                            role_id    BIGINT    NOT NULL,
                            created_at TIMESTAMP NOT NULL,
                            CONSTRAINT pk_user_roles PRIMARY KEY (id),
                            CONSTRAINT uk_user_roles UNIQUE (user_id, role_id)
);

/* =========================
   contents
========================= */
CREATE TABLE contents (
                          id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          uuid          UUID      NOT NULL,
                          external_id   VARCHAR,
                          type          VARCHAR   NOT NULL,
                          title         VARCHAR   NOT NULL,
                          description   VARCHAR   NOT NULL,
                          thumbnail_url VARCHAR,
                          created_at    TIMESTAMP NOT NULL,
                          updated_at    TIMESTAMP,
                          CONSTRAINT pk_contents PRIMARY KEY (id),
                          CONSTRAINT uk_contents_uuid UNIQUE (uuid),
                          CONSTRAINT uk_contents_external_id UNIQUE (external_id)
);

/* =========================
   tags
========================= */
CREATE TABLE tags (
                      id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      uuid       UUID      NOT NULL,
                      name       VARCHAR   NOT NULL,
                      created_at TIMESTAMP NOT NULL,
                      updated_at TIMESTAMP,
                      CONSTRAINT pk_tags PRIMARY KEY (id),
                      CONSTRAINT uk_tags_uuid UNIQUE (uuid),
                      CONSTRAINT uk_tags_name UNIQUE (name)
);

/* =========================
   content_tags (N:M)
========================= */
CREATE TABLE content_tags (
                              id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              content_id BIGINT    NOT NULL,
                              tag_id     BIGINT    NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              CONSTRAINT pk_content_tags PRIMARY KEY (id),
                              CONSTRAINT uk_content_tags UNIQUE (content_id, tag_id)
);

/* =========================
   playlists
========================= */
CREATE TABLE playlists (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                           uuid        UUID      NOT NULL,
                           title       VARCHAR   NOT NULL,
                           user_id     BIGINT    NOT NULL,
                           description TEXT      NOT NULL,
                           created_at  TIMESTAMP NOT NULL,
                           updated_at  TIMESTAMP,
                           CONSTRAINT pk_playlists PRIMARY KEY (id),
                           CONSTRAINT uk_playlists_uuid UNIQUE (uuid)
);

/* =========================
   playlist_contents (N:M)
========================= */
CREATE TABLE playlist_contents (
                                   id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   content_id  BIGINT    NOT NULL,
                                   playlist_id BIGINT    NOT NULL,
                                   created_at  TIMESTAMP NOT NULL,
                                   CONSTRAINT pk_playlist_contents PRIMARY KEY (id),
                                   CONSTRAINT uk_playlist_contents UNIQUE (content_id, playlist_id)
);

/* =========================
   subscribes
========================= */
CREATE TABLE subscribes (
                            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            uuid        UUID      NOT NULL,
                            user_id     BIGINT    NOT NULL,
                            playlist_id BIGINT    NOT NULL,
                            created_at  TIMESTAMP NOT NULL,
                            CONSTRAINT pk_subscribes PRIMARY KEY (id),
                            CONSTRAINT uk_subscribes UNIQUE (user_id, playlist_id)
);

/* =========================
   follows (self N:M)
========================= */
CREATE TABLE follows (
                         id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         uuid        UUID      NOT NULL,
                         follower_id BIGINT    NOT NULL,
                         followee_id BIGINT    NOT NULL,
                         created_at  TIMESTAMP NOT NULL,
                         CONSTRAINT pk_follows PRIMARY KEY (id),
                         CONSTRAINT uk_follows UNIQUE (follower_id, followee_id)
);

/* =========================
   reviews
========================= */
CREATE TABLE reviews (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         uuid       UUID      NOT NULL,
                         user_id    BIGINT    NOT NULL,
                         content_id BIGINT    NOT NULL,
                         rating     DOUBLE PRECISION NOT NULL,
                         text       TEXT      NOT NULL,
                         created_at TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP,
                         CONSTRAINT pk_reviews PRIMARY KEY (id),
                         CONSTRAINT uk_reviews_uuid UNIQUE (uuid),
                         CONSTRAINT uk_reviews UNIQUE (user_id, content_id)
);

/* =========================
   direct conversations / messages
========================= */
CREATE TABLE direct_conversations (
                                      id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      uuid       UUID      NOT NULL,
                                      creator_id BIGINT    NOT NULL,
                                      join_id    BIGINT    NOT NULL,
                                      created_at TIMESTAMP NOT NULL,
                                      CONSTRAINT pk_direct_conversations PRIMARY KEY (id),
                                      CONSTRAINT uk_direct_conversations_uuid UNIQUE (uuid)
);

CREATE TABLE direct_messages (
                                 id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 uuid            UUID      NOT NULL,
                                 sender_id       BIGINT    NOT NULL,
                                 receiver_id     BIGINT    NOT NULL,
                                 conversation_id BIGINT    NOT NULL,
                                 content         TEXT      NOT NULL,
                                 read_status     BOOLEAN   NOT NULL,
                                 created_at      TIMESTAMP NOT NULL,
                                 CONSTRAINT pk_direct_messages PRIMARY KEY (id),
                                 CONSTRAINT uk_direct_messages_uuid UNIQUE (uuid)
);

/* =========================
   temporary_password
========================= */
CREATE TABLE temporary_password (
                                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    user_id    BIGINT    NOT NULL,
                                    password   VARCHAR   NOT NULL,
                                    created_at TIMESTAMP NOT NULL,
                                    CONSTRAINT pk_temporary_password PRIMARY KEY (id)
);

/* =========================
   notifications
========================= */
CREATE TABLE notifications (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               uuid        UUID      NOT NULL,
                               level       VARCHAR   NOT NULL,
                               receiver_id UUID    NOT NULL,
                               title       VARCHAR   NOT NULL,
                               content     TEXT,
                               created_at  TIMESTAMP NOT NULL,
                               CONSTRAINT pk_notifications PRIMARY KEY (id),
                               CONSTRAINT uk_notifications_uuid UNIQUE (uuid),
                               CONSTRAINT uk_notifications_receiver_id UNIQUE (receiver_id)
);


ALTER TABLE profiles
    ADD CONSTRAINT fk_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE content_tags
    ADD CONSTRAINT fk_content_tags_content
        FOREIGN KEY (content_id) REFERENCES contents (id),
    ADD CONSTRAINT fk_content_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE playlists
    ADD CONSTRAINT fk_playlists_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE playlist_contents
    ADD CONSTRAINT fk_playlist_contents_content
        FOREIGN KEY (content_id) REFERENCES contents (id),
    ADD CONSTRAINT fk_playlist_contents_playlist
        FOREIGN KEY (playlist_id) REFERENCES playlists (id);

ALTER TABLE subscribes
    ADD CONSTRAINT fk_subscribes_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_subscribes_playlist
        FOREIGN KEY (playlist_id) REFERENCES playlists (id);

ALTER TABLE follows
    ADD CONSTRAINT fk_follows_follower
        FOREIGN KEY (follower_id) REFERENCES users (id),
    ADD CONSTRAINT fk_follows_followee
        FOREIGN KEY (followee_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    ADD CONSTRAINT fk_reviews_content
        FOREIGN KEY (content_id) REFERENCES contents (id);

ALTER TABLE direct_messages
    ADD CONSTRAINT fk_direct_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES direct_conversations (id);

ALTER TABLE temporary_password
    ADD CONSTRAINT fk_temporary_password_user
        FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE BATCH_JOB_INSTANCE  (
                                     JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
                                     VERSION BIGINT ,
                                     JOB_NAME VARCHAR(100) NOT NULL,
                                     JOB_KEY VARCHAR(32) NOT NULL,
                                     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
                                      JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                      VERSION BIGINT  ,
                                      JOB_INSTANCE_ID BIGINT NOT NULL,
                                      CREATE_TIME TIMESTAMP NOT NULL,
                                      START_TIME TIMESTAMP DEFAULT NULL ,
                                      END_TIME TIMESTAMP DEFAULT NULL ,
                                      STATUS VARCHAR(10) ,
                                      EXIT_CODE VARCHAR(2500) ,
                                      EXIT_MESSAGE VARCHAR(2500) ,
                                      LAST_UPDATED TIMESTAMP,
                                      constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                          references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID BIGINT NOT NULL ,
                                             PARAMETER_NAME VARCHAR(100) NOT NULL ,
                                             PARAMETER_TYPE VARCHAR(100) NOT NULL ,
                                             PARAMETER_VALUE VARCHAR(2500) ,
                                             IDENTIFYING CHAR(1) NOT NULL ,
                                             constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                 references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
                                       STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                       VERSION BIGINT NOT NULL,
                                       STEP_NAME VARCHAR(100) NOT NULL,
                                       JOB_EXECUTION_ID BIGINT NOT NULL,
                                       CREATE_TIME TIMESTAMP NOT NULL,
                                       START_TIME TIMESTAMP DEFAULT NULL ,
                                       END_TIME TIMESTAMP DEFAULT NULL ,
                                       STATUS VARCHAR(10) ,
                                       COMMIT_COUNT BIGINT ,
                                       READ_COUNT BIGINT ,
                                       FILTER_COUNT BIGINT ,
                                       WRITE_COUNT BIGINT ,
                                       READ_SKIP_COUNT BIGINT ,
                                       WRITE_SKIP_COUNT BIGINT ,
                                       PROCESS_SKIP_COUNT BIGINT ,
                                       ROLLBACK_COUNT BIGINT ,
                                       EXIT_CODE VARCHAR(2500) ,
                                       EXIT_MESSAGE VARCHAR(2500) ,
                                       LAST_UPDATED TIMESTAMP,
                                       constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                           references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
                                               STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                               SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                               SERIALIZED_CONTEXT TEXT ,
                                               constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                   references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
                                              JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT TEXT ,
                                              constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
