-- contents_stats.id 자동증가 설정
ALTER TABLE contents_stats
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- playlists_stats.id 자동증가 설정
ALTER TABLE playlists_stats
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;