/* =========================
   watching_sessions (프로필 페이지 - 현재 시청 중인 콘텐츠 조회용)
   watcher_id = users.id
========================= */
CREATE TABLE watching_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid            UUID      NOT NULL,
    watcher_id      BIGINT    NOT NULL,
    content_id      BIGINT    NOT NULL,
    last_position   BIGINT    NOT NULL DEFAULT 0,
    duration        BIGINT,
    status          VARCHAR(20) NOT NULL DEFAULT 'WATCHING',
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_watching_sessions PRIMARY KEY (id),
    CONSTRAINT uk_watching_sessions_uuid UNIQUE (uuid),
    CONSTRAINT uk_watching_sessions_watcher_content UNIQUE (watcher_id, content_id)
);

ALTER TABLE watching_sessions
    ADD CONSTRAINT fk_watching_sessions_watcher
        FOREIGN KEY (watcher_id) REFERENCES users (id),
    ADD CONSTRAINT fk_watching_sessions_content
        FOREIGN KEY (content_id) REFERENCES contents (id);

CREATE INDEX idx_watching_sessions_watcher_status ON watching_sessions (watcher_id, status);
CREATE INDEX idx_watching_sessions_updated_at ON watching_sessions (updated_at);
